# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Issues & fixes by Shev
email: bliz937@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My own tech blog site; issues and fixes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bliz937.github.io" # the base hostname & protocol for your site
twitter_username: bliz7
github_username:  bliz937
rescuetime_ref:   1013725

# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-gist
